/* CashFlow Web — frontend only. Publishable key is intended for public clients; protect rows with RLS. */
const SUPABASE_URL = 'https://ryrenikoyopjqyhmqanl.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_Xsu52XLtDg8Zd2E5fn2mRg_Bp0UGCxt';
const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const $ = (id) => document.getElementById(id);
const categories = {
  income: ['Skripsi', 'Makalah', 'Jurnal', 'Jasa Desain', 'Lainnya'],
  expense: ['Fee / Gaji Karyawan', 'Bonus', 'HPP', 'Marketing — Instagram']
};
const categoryIcons = {
  'Skripsi':'✎', 'Makalah':'▤', 'Jurnal':'◈', 'Jasa Desain':'◇', 'Lainnya':'•',
  'Fee / Gaji Karyawan':'♙', 'Bonus':'✦', 'HPP':'▣', 'Marketing — Instagram':'◎'
};
let currentUser = null;
let transactions = [];
let currentPage = 'dashboard';
let pendingDeleteId = null;
let authMode = 'login';
let toastTimer;
const monthNow = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; };
const todayISO = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const money = (n) => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0).replace(/\u00a0/g,'');
const escapeHTML = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notify(message, error=false){ const t=$('toast');t.textContent=message;t.classList.toggle('error',error);t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3800); }
function setAuthMode(mode){authMode=mode;const login=mode==='login';$('authTitle').textContent=login?'Selamat datang kembali':'Buat akun CashFlow';$('authDescription').textContent=login?'Masuk untuk melihat dan mengelola keuanganmu.':'Daftar dengan email untuk menyimpan transaksi di akunmu.';$('authSubmit').textContent=login?'MASUK':'BUAT AKUN';$('authSwitchText').textContent=login?'Belum punya akun?':'Sudah punya akun?';$('authSwitch').textContent=login?'Buat akun':'Masuk';$('authPassword').autocomplete=login?'current-password':'new-password';}
function showApp(){ $('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('userEmail').textContent=currentUser?.email||'Akun pengguna'; }
function showAuth(){ $('appView').classList.add('hidden');$('authView').classList.remove('hidden'); }
async function handleAuth(event){event.preventDefault();const email=$('authEmail').value.trim();const password=$('authPassword').value;if(!email||!password)return;const button=$('authSubmit');button.disabled=true;button.textContent='MEMPROSES…';try{let result;if(authMode==='login')result=await db.auth.signInWithPassword({email,password});else result=await db.auth.signUp({email,password});if(result.error)throw result.error;if(authMode==='signup'&&!result.data.session){notify('Pendaftaran berhasil. Periksa email untuk konfirmasi sebelum masuk.');setAuthMode('login');return;}currentUser=result.data.user;showApp();await loadTransactions();notify(authMode==='signup'?'Akun berhasil dibuat.':'Berhasil masuk.');}catch(e){notify(authError(e),true);}finally{button.disabled=false;button.textContent=authMode==='login'?'MASUK':'BUAT AKUN';}}
function authError(e){const m=e?.message||'Terjadi kesalahan.';if(/Invalid login credentials/i.test(m))return 'Email atau password tidak cocok.';if(/Email not confirmed/i.test(m))return 'Email belum dikonfirmasi. Periksa kotak masuk email.';if(/already registered/i.test(m))return 'Email ini sudah terdaftar. Silakan masuk.';return m;}
async function handleLogout(){const {error}=await db.auth.signOut();if(error){notify(error.message,true);return;}currentUser=null;transactions=[];showAuth();setAuthMode('login');notify('Kamu sudah keluar.');}
function goTo(page){currentPage=page;const titles={dashboard:['OVERVIEW','Dashboard','Ikhtisar keuanganmu bulan ini.'],transactions:['LEDGER','Transaksi','Lihat dan kelola transaksi tersimpan.'],summary:['ANALYTICS','Ringkasan bulanan','Pemasukan, pengeluaran, dan distribusi kategori.'],add:['NEW ENTRY','Tambah transaksi','Catat pemasukan atau pengeluaran baru.']};const info=titles[page]||titles.dashboard;$('pageEyebrow').textContent=info[0];$('pageTitle').textContent=info[1];$('pageSubtitle').textContent=info[2];for(const p of ['dashboard','transactions','summary','add'])$(p+'Page').classList.toggle('hidden',p!==page);document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('sidebar').classList.remove('open');if(page==='add'){$('txDate').value=todayISO();refreshCategories();$('txDescription').focus({preventScroll:true});}render();window.scrollTo({top:0,behavior:'smooth'});}
function selectedMonth(){return $('globalMonth').value||monthNow();}
function forSelectedMonth(){const m=selectedMonth();return transactions.filter(t=>String(t.date).startsWith(m));}
function totals(rows){return rows.reduce((a,t)=>{if(t.type==='income')a.income+=Number(t.amount);else a.expense+=Number(t.amount);return a;},{income:0,expense:0});}
async function loadTransactions(){if(!currentUser)return;const {data,error}=await db.from('transactions').select('id,user_id,date,type,category,description,amount,created_at').order('date',{ascending:false}).order('created_at',{ascending:false}).limit(5000);if(error){notify('Tidak bisa memuat transaksi: '+error.message,true);return;}transactions=data||[];render();}
function render(){if(!currentUser)return;const rows=forSelectedMonth();const {income,expense}=totals(rows);const balance=income-expense;$('dashIncome').textContent=money(income);$('dashExpense').textContent=money(expense);$('dashBalance').textContent=money(balance);$('positionBalance').textContent=money(balance);$('positionIncome').textContent=money(income);$('positionExpense').textContent=money(expense);const total=income+expense;$('incomeRatio').style.width=(total?income/total*100:0)+'%';$('expenseRatio').style.width=(total?expense/total*100:0)+'%';renderRecent();renderTable(rows);renderSummary(rows,income,expense,balance);}
function renderRecent(){const recent=[...transactions].sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.created_at).localeCompare(String(a.created_at))).slice(0,6);$('recentTransactions').innerHTML=recent.map(t=>`<div class="transaction-item"><div class="tx-icon">${escapeHTML(categoryIcons[t.category]||'•')}</div><div><div class="tx-title">${escapeHTML(t.description)}</div><div class="tx-meta">${escapeHTML(t.category)} · ${escapeHTML(t.date)}</div></div><div class="tx-amount ${t.type==='income'?'green':'red'}">${t.type==='income'?'+':'−'}${money(t.amount)}</div></div>`).join('');$('recentEmpty').classList.toggle('hidden',recent.length>0);}
function renderTable(rows){$('transactionCount').textContent=`${rows.length} transaksi`;const sorted=[...rows].sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.created_at).localeCompare(String(a.created_at)));$('transactionRows').innerHTML=sorted.map(t=>`<tr><td>${escapeHTML(t.date)}</td><td><span class="${t.type==='income'?'green':'red'}">${t.type==='income'?'Pemasukan':'Pengeluaran'}</span></td><td>${escapeHTML(t.category)}</td><td>${escapeHTML(t.description)}</td><td class="amount-cell ${t.type==='income'?'green':'red'}">${t.type==='income'?'+':'−'}${money(t.amount)}</td><td><button class="delete-button" data-delete="${escapeHTML(t.id)}" aria-label="Hapus transaksi">Hapus</button></td></tr>`).join('');$('transactionsEmpty').classList.toggle('hidden',rows.length>0);}
function renderSummary(rows,income,expense,balance){$('summaryBalance').textContent=money(balance);$('summaryIncome').textContent=money(income);$('summaryExpense').textContent=money(expense);const max=Math.max(income,expense,1);$('summaryIncomeBar').style.width=(income/max*100)+'%';$('summaryExpenseBar').style.width=(expense/max*100)+'%';$('summaryIncomeBarText').textContent=money(income);$('summaryExpenseBarText').textContent=money(expense);const expenses=rows.filter(t=>t.type==='expense').reduce((acc,t)=>{acc[t.category]=(acc[t.category]||0)+Number(t.amount);return acc;},{});const list=Object.entries(expenses).sort((a,b)=>b[1]-a[1]);const maxCat=Math.max(...list.map(x=>x[1]),1);$('categoryBreakdown').innerHTML=list.map(([cat,amount])=>`<div><div class="category-row-head"><span>${escapeHTML(cat)}</span><span>${money(amount)} · ${(expense?amount/expense*100:0).toFixed(1)}%</span></div><div class="category-track"><div class="category-fill" style="width:${amount/maxCat*100}%"></div></div></div>`).join('');$('categoryEmpty').classList.toggle('hidden',list.length>0);}
function refreshCategories(){const type=$('txType').value;const select=$('txCategory');select.innerHTML=categories[type].map(c=>`<option value="${escapeHTML(c)}">${escapeHTML(c)}</option>`).join('');}
function parseAmount(value){const raw=String(value).trim().replace(/[.\s]/g,'').replace(/,/g,'');if(!/^\d+$/.test(raw))return NaN;return Number(raw);}
async function saveTransaction(event){event.preventDefault();if(!currentUser)return;const amount=parseAmount($('txAmount').value);const description=$('txDescription').value.trim();const date=$('txDate').value;if(!description){notify('Keterangan wajib diisi.',true);return;}if(!Number.isSafeInteger(amount)||amount<=0){notify('Masukkan jumlah rupiah berupa angka lebih dari nol.',true);return;}if(!date||Number.isNaN(Date.parse(date))){notify('Pilih tanggal transaksi yang valid.',true);return;}const payload={user_id:currentUser.id,date,type:$('txType').value,category:$('txCategory').value,description,amount};const button=$('transactionForm').querySelector('[type="submit"]');button.disabled=true;button.textContent='MENYIMPAN…';try{const {error}=await db.from('transactions').insert(payload);if(error)throw error;$('txDescription').value='';$('txAmount').value='';$('txDate').value=todayISO();$('globalMonth').value=date.slice(0,7);await loadTransactions();goTo('dashboard');notify('Transaksi berhasil disimpan.');}catch(e){notify('Gagal menyimpan transaksi: '+e.message,true);}finally{button.disabled=false;button.textContent='SIMPAN TRANSAKSI →';}}
function openDelete(id){pendingDeleteId=id;$('deleteDialog').showModal();}
async function deleteTransaction(){if(!pendingDeleteId)return;const id=pendingDeleteId;pendingDeleteId=null;const {error}=await db.from('transactions').delete().eq('id',id);if(error){notify('Gagal menghapus transaksi: '+error.message,true);return;}transactions=transactions.filter(t=>String(t.id)!==String(id));$('deleteDialog').close();render();notify('Transaksi dihapus.');}
function exportCSV(){const rows=[...transactions].sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(!rows.length){notify('Belum ada transaksi untuk diekspor.',true);return;}const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv='tanggal,jenis,kategori,keterangan,jumlah\r\n'+rows.map(t=>[t.date,t.type==='income'?'pemasukan':'pengeluaran',t.category,t.description,t.amount].map(quote).join(',')).join('\r\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`cashflow_${todayISO()}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);notify('Ekspor CSV berhasil dibuat.');}
function wire(){ $('authForm').addEventListener('submit',handleAuth);$('authSwitch').addEventListener('click',()=>setAuthMode(authMode==='login'?'signup':'login'));$('logoutBtn').addEventListener('click',handleLogout);$('exportBtn').addEventListener('click',exportCSV);$('topAdd').addEventListener('click',()=>goTo('add'));$('mobileAdd').addEventListener('click',()=>goTo('add'));$('menuToggle').addEventListener('click',()=>$('sidebar').classList.toggle('open'));$('globalMonth').addEventListener('change',render);$('txType').addEventListener('change',refreshCategories);$('transactionForm').addEventListener('submit',saveTransaction);$('confirmDelete').addEventListener('click',e=>{e.preventDefault();deleteTransaction();});document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){goTo(nav.dataset.page);return;}const goto=e.target.closest('[data-goto]');if(goto){goTo(goto.dataset.goto);return;}const del=e.target.closest('[data-delete]');if(del)openDelete(del.dataset.delete);});$('globalMonth').value=monthNow();$('txDate').value=todayISO();refreshCategories();}
async function init(){wire();if('serviceWorker'in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}const {data:{session}}=await db.auth.getSession();if(session?.user){currentUser=session.user;showApp();await loadTransactions();}else showAuth();db.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session?.user){currentUser=session.user;showApp();await loadTransactions();}else if(event==='SIGNED_OUT'){currentUser=null;transactions=[];showAuth();}});}
init();
